# Generated by Django 4.1.2 on 2022-11-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0003_alter_cabinets_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='number',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
