# Generated by Django 4.1.2 on 2022-11-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0005_alter_doctors_cabinet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('auth_token', models.CharField(max_length=100)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='doctors.doctors')),
            ],
        ),
    ]
