# Generated by Django 4.1.2 on 2022-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptions',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
