# Generated by Django 4.1.2 on 2022-11-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0002_alter_cabinets_days_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('cabinet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cabinets.cabinets')),
            ],
        ),
    ]
