# Generated by Django 4.1.2 on 2022-11-05 20:12

import cabinets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0002_alter_cabinets_days_working'),
        ('doctors', '0002_alter_doctors_cabinet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='cabinet_id',
            field=models.ForeignKey(default=cabinets.models.Cabinets, null=True, on_delete=django.db.models.deletion.PROTECT, to='cabinets.cabinets'),
        ),
    ]
