# Generated by Django 4.1.2 on 2022-11-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0004_alter_cabinets_number'),
        ('doctors', '0004_alter_doctors_cabinet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='cabinet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cabinet_number', to='cabinets.cabinets', to_field='number'),
        ),
    ]
