# Generated by Django 4.1.2 on 2022-10-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcrud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCrud',
        ),
    ]
