# Generated by Django 4.1.2 on 2022-10-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcrud', '0002_delete_testcrud'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=250)),
            ],
        ),
    ]
